### ISSUE TITLE
good job

### ISSUE THREAD

**Issue by pesh12** [itemah26/HackYourFuture-JavaScript3-HWk#1]
https://github.com/itemah26/HackYourFuture-JavaScript3-HWk/blob/e7708254f6e9ea1fc9c4579deb6f8c681e749872/week1/script.js#L91

in this line there was no other way than you did.  You have condensed repos like we did before. Unfortunately we couldn't explain in the class, anyways.
And I understand the error messages better when I checked your code..
Good Job brother

**Comment by itemah26** [comment]
Thanks Bro
